### ISSUE TITLE
Package & Tests Broken: Errors internal to this package must be fixed to function

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-cooperative/linter-shellcheck-pulsar#2]
After forking this package, it became apparent that there are errors being thrown within this package causing it to fail to load, and become broken.

Here is a full log from the GHA `pulsar --test spec` command:

<details>
<summary>GHA Test Log</summary>

```
/usr/bin/sudo apt-get install -y xvfb x11-xserver-utils
Reading package lists...
Building dependency tree...
Reading state information...
xvfb is already the newest version (2:1.20.13-1ubuntu1~20.04.12).
Suggested packages:
  nickle cairo-[5](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:6)c xorg-docs-core
The following NEW packages will be installed:
  x11-xserver-utils
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 1[6](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:7)2 kB of archives.
After this operation, 51[7](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:8) kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 x11-xserver-utils amd64 7.7+[8](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:9) [162 kB]
Fetched 162 kB in 0s (2606 kB/s)
Selecting previously unselected package x11-xserver-utils.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... [9](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:10)0%
(Reading database ... 95%
(Reading database ... [10](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:11)0%
(Reading database ... 300930 files and directories currently installed.)
Preparing to unpack .../x[11](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:12)-xserver-utils_7.7+8_amd64.deb ...
Unpacking x11-xserver-utils (7.7+8) ...
Setting up x11-xserver-utils (7.7+8) ...
Processing triggers for man-db (2.9.1-1) ...
Command: pulsar --test spec
/usr/bin/xvfb-run --auto-servernum pulsar --test spec
(node:2611) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.73SJBF'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(Use `exe --trace-warnings ...` to show where the warning was created)
(node:2611) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.IVXvRD'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:2611) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.8rF8uE'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:2611) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.99m1XD'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:2611) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:2611) Electron: Loading non-context-aware native module in renderer: '/opt/Pulsar/resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
FFFFFF

The ShellCheck provider for Linter
  implements useProjectCwd and
    it uses file-relative source= directives by default
      Error: Failed to load package 'linter-shellcheck'
        at PackageManager.activatePackage (/opt/Pulsar/resources/app.asar/src/package-manager.js:776:29)
        at linter-shellcheck-spec.js:22:45
        at jasmine.Spec.middleware (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/jasmine-fix/index.js:49:21)
      AssertionError: filePath must be a string
        AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: filePath must be a string
        at validate (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/helpers.js:80:24)
        at execProxy (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/index.js:152:39)
        at Object.exec (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/atom-linter/lib/helpers.js:105:19)
        at lint (main.js:79:24)
        at linter-shellcheck-spec.js:61:30
    it errors for file-relative source= path with useProjectCwd = true
      Error: Failed to load package 'linter-shellcheck'
        at PackageManager.activatePackage (/opt/Pulsar/resources/app.asar/src/package-manager.js:776:29)
        at linter-shellcheck-spec.js:22:45
        at jasmine.Spec.middleware (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/jasmine-fix/index.js:49:21)
      AssertionError: filePath must be a string
        AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: filePath must be a string
        at validate (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/helpers.js:80:24)
        at execProxy (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/index.js:152:39)
        at Object.exec (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/atom-linter/lib/helpers.js:105:19)
        at lint (main.js:79:24)
        at linter-shellcheck-spec.js:68:30
    it uses project-relative source= directives via setting (based at fixtures/)
      Error: Failed to load package 'linter-shellcheck'
        at PackageManager.activatePackage (/opt/Pulsar/resources/app.asar/src/package-manager.js:776:29)
        at linter-shellcheck-spec.js:22:45
        at jasmine.Spec.middleware (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/jasmine-fix/index.js:49:21)
      AssertionError: filePath must be a string
        AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: filePath must be a string
        at validate (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/helpers.js:80:24)
        at execProxy (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/index.js:152:39)
        at Object.exec (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/atom-linter/lib/helpers.js:105:19)
        at lint (main.js:79:24)
        at linter-shellcheck-spec.js:76:30
    it errors for project-relative source= path with useProjectCwd = false (based at fixtures/)
      Error: Failed to load package 'linter-shellcheck'
        at PackageManager.activatePackage (/opt/Pulsar/resources/app.asar/src/package-manager.js:776:29)
        at linter-shellcheck-spec.js:22:45
        at jasmine.Spec.middleware (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/jasmine-fix/index.js:49:21)
      AssertionError: filePath must be a string
        AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: filePath must be a string
        at validate (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/helpers.js:80:24)
        at execProxy (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/index.js:152:39)
        at Object.exec (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/atom-linter/lib/helpers.js:105:19)
        at lint (main.js:79:24)
        at linter-shellcheck-spec.js:83:30
  it finds nothing wrong with a valid file
    Error: Failed to load package 'linter-shellcheck'
      at PackageManager.activatePackage (/opt/Pulsar/resources/app.asar/src/package-manager.js:776:29)
      at linter-shellcheck-spec.js:22:45
      at jasmine.Spec.middleware (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/jasmine-fix/index.js:49:21)
    AssertionError: filePath must be a string
      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: filePath must be a string
      at validate (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/helpers.js:80:24)
      at execProxy (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/index.js:152:39)
      at Object.exec (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/atom-linter/lib/helpers.js:105:19)
      at lint (main.js:79:24)
      at linter-shellcheck-spec.js:33:28
  it handles messages from ShellCheck
    Error: Failed to load package 'linter-shellcheck'
      at PackageManager.activatePackage (/opt/Pulsar/resources/app.asar/src/package-manager.js:776:29)
      at linter-shellcheck-spec.js:22:45
      at jasmine.Spec.middleware (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/jasmine-fix/index.js:49:21)
    AssertionError: filePath must be a string
      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: filePath must be a string
      at validate (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/helpers.js:80:24)
      at execProxy (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/sb-exec/lib/index.js:152:39)
      at Object.exec (/home/runner/work/linter-shellcheck-pulsar/linter-shellcheck-pulsar/node_modules/atom-linter/lib/helpers.js:105:19)
      at lint (main.js:79:24)
      at linter-shellcheck-spec.js:42:28


Finished in 0.421 seconds
6 tests, [12](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/actions/runs/7366657853/job/20049125911?pr=1#step:9:13) assertions, 12 failures, 0 skipped

/usr/bin/bash /home/runner/work/_actions/coactions/setup-xvfb/v1.0.1/dist/cleanup.sh
/usr/bin/bash: /home/runner/work/_actions/coactions/setup-xvfb/v1.0.1/dist/cleanup.sh: No such file or directory
Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```

</details>

**Comment by confused-Techie** [comment]
To avoid the issues seen in the [`pulsar-ternjs`](https://github.com/pulsar-cooperative/pulsar-ternjs) package, we will delay publication of this package, until the errors here are resolved.

Since we don't want to publish a known broken package, and have users install it, assuming everything will work.

So whoever does eventually close this issue, once said PR is merged, an Admin **must** run the initial publication workflow.
